version: '3.4'

volumes:
  postgres-data:

networks:
  app-network:

services:
  MyDatabase:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "9091:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  someapi:
    build:
      context: .
      dockerfile: SomeApi/Dockerfile
    ports:
      - "5002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=MyDatabase;Database=mydb;Username=postgres;Password=123
    depends_on:
      - MyDatabase
    networks:
      - app-network

